spring:
  application:
    name: monitoring-api

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:telemetry_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6380}

server:
  port: 8083